version: 2

project_name: polyforge

env_files:
    github_token: ~/.config/goreleaser/github_token

before:
    hooks:
        - go tool goimports -format-only -v -w .

        - go vet
        - go mod tidy
        - go mod vendor

builds:
    -   env:
            - CGO_ENABLED=0
        ldflags:
            - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.sources=no-include"
        goos:
            - linux
            - darwin

archives:
    -   format: tar.gz
        name_template: >-
            {{ .ProjectName }}-
            {{- .Os }}-
            {{- if eq .Arch "amd64" }}x86-64
            {{- else if eq .Arch "386" }}i386
            {{- else }}{{ .Arch }}{{ end }}
            {{- if .Arm }}v{{ .Arm }}{{ end }}
        format_overrides:
            -   goos: windows
                format: zip

brews:
    -   name: polyforge

        directory: Formula

        commit_author:
            name: Jacob B. Sanders
            email: 60639231+Segmentational@users.noreply.github.com

        commit_msg_template: "[Chore]: Brew Formula Bump ({{ .ProjectName }}), {{ .Tag }}"

        # caveats: |
        #     Internal Usage Only

        homepage: "https://github.com/polyium/polyforge"

        description: "CLI"

        license: "MIT"

        skip_upload: false

        download_strategy: CurlDownloadStrategy

        dependencies: [ ]

        conflicts:
            - polyforge

        repository:
            branch: main
            owner: polyium
            name: homebrew-taps

changelog:
    use: github-native
