version: 2

project_name: polyforge

env_files:
    github_token: ~/.config/goreleaser/github_token

before:
    hooks:
        - go tool goimports -format-only -v -w .

        - go vet
        - go mod tidy
        - go mod vendor

builds:
    -   env:
            - CGO_ENABLED=0
        ldflags:
            - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.sources=no-include"
        goos:
            - linux
            - darwin

archives:
    -   formats: [ "tar.gz" ]
        name_template: >-
            {{ .ProjectName }}-
            {{- .Os }}-
            {{- if eq .Arch "amd64" }}x86-64
            {{- else if eq .Arch "386" }}i386
            {{- else }}{{ .Arch }}{{ end }}
            {{- if .Arm }}v{{ .Arm }}{{ end }}
        format_overrides:
            -   goos: windows
                formats: [ "zip" ]

homebrew_casks:
    -   name: polyforge

        binary: polyforge

        # This information will be used to build the URL section of your Cask.
        #
        # You can set the template, as well as additional parameters.
        # These parameters can be used to provide extra headers, cookies, or other
        # download requirements for your application.
        # See https://docs.brew.sh/Cask-Cookbook#additional-url-parameters for more details.
        #
        # All fields are optional.
        url:
            verified: github.com/polyium/polyforge

            # Download strategy or format specification
            # See official Cask Cookbook for allowed values.
            # Templates: allowed.
            using: ":homebrew_curl"

            # HTTP cookies to send with the download request
            # Templates: allowed.
            cookies:
                license: "accept-backup"

            # Additional HTTP headers
            # Templates: allowed.
            headers:
                - "X-Version: {{ .Version }}"

        # Optional: if your app/binary isn't signed and notarized, you'll need this:
        hooks:
            post:
                # replace foo with the actual binary name
                install: |
                    if OS.mac?
                      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
                    end

        commit_author:
            name: Jacob B. Sanders
            email: 60639231+Segmentational@users.noreply.github.com

        commit_msg_template: "[Chore]: Brew Formula Bump ({{ .ProjectName }}), {{ .Tag }}"

        homepage: "https://github.com/polyium/polyforge"

        description: "CLI"

        license: "MIT"

        skip_upload: false

        repository:
            branch: main
            owner: polyium
            name: homebrew-taps

changelog:
    use: github-native
