---
repos:
    -   repo: "https://github.com/pre-commit/pre-commit-hooks"
        rev: "v6.0.0"
        hooks:
            -   id: check-added-large-files
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-executables-have-shebangs
            -   id: check-json
            -   id: check-symlinks
            -   id: check-vcs-permalinks
            -   id: check-xml
            -   id: check-yaml
                args: [ --allow-multiple-documents ]
            -   id: mixed-line-ending
            -   id: trailing-whitespace
            -   id: end-of-file-fixer

    -   repo: https://github.com/gitleaks/gitleaks
        rev: v8.18.2
        hooks:
            -   id: gitleaks
